from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('product_list/',views.product_list,name='product_list'),
    path('product_detail/<int:pk>/',views.product_detail,name='product_detail'),
    path('cart/<int:pk>/',views.cart,name='cart'),
    path('my_account/',views.my_account,name='my_account'),
    path('wishlist/<int:pk>/',views.wishlist,name='wishlist'),
    path('login/',views.login,name='login'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout,name='logout'),
    path('seller_add_product/',views.seller_add_product,name='seller_add_product'),
    path('seller_index/',views.seller_index,name='seller_index'),
    path('seller_view_product/',views.seller_view_product,name='seller_view_product'),
    path('seller_edit_product/<int:pk>/',views.seller_edit_product,name='seller_edit_product'),
    path('seller_product_detail/<int:pk>/',views.seller_product_detail,name='seller_product_detail'),
    path('seller_delete_product/<int:pk>/',views.seller_delete_product,name='seller_delete_product'),
    path('mywishlist/',views.mywishlist,name='mywishlist'),
    path('remove_from_wishlist/<int:pk>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('mycart/',views.mycart,name='mycart'),
    path('remove_from_cart/<int:pk>/',views.remove_from_cart,name='remove_from_cart'),
    path('change_qty/',views.change_qty,name='change_qty'),
    path('pay/',views.initiate_payment,name='pay'),
    path('callback/',views.callback,name='callback'),
    path('myorder/',views.myorder,name='myorder'),
    path('user_order_details/<int:pk>/',views.user_order_details,name='user_order_details'),
    path('user_edit_profile/',views.user_edit_profile,name='user_edit_profile'),
    path('user_product_search/',views.user_product_search,name='user_product_search'),
    path('verify_otp/',views.verify_otp,name='verify_otp'),
    path('change_password/',views.change_password,name='change_password'),
    path('enter_email/',views.enter_email,name='enter_email'),
    path('forgot_verify_otp/',views.forgot_verify_otp,name='forgot_verify_otp'),
    path('new_password/',views.new_password,name='new_password'),
    path('ajax/login_validate_email/',views.login_validate_email,name='login_validate_email'),
    path('ajax/signup_validate_email/',views.signup_validate_email,name='signup_validate_email'),
]